const images={"Café":"https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80","Bebidas frías":"https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=600&q=80","Desayunos":"https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=600&q=80","Comidas":"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=600&q=80","Postres":"https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=600&q=80"};
const baseProducts=[
['Espresso doble','Café','Intenso, dulce y equilibrado.',24],['Cappuccino','Café','Doble espresso, leche sedosa y espuma.',32],['Latte de miel','Café','Miel local, canela y leche vaporizada.',38],['Americano','Café','Espresso y agua, limpio y brillante.',26],['Flat white','Café','Café con microespuma aterciopelada.',34],['Mocha de la casa','Café','Chocolate oscuro, espresso y leche.',40],['Cold brew cítrico','Bebidas frías','Extracción en frío, naranja y tónica.',42],['Matcha cloud','Bebidas frías','Matcha ceremonial y nube de vainilla.',44],['Té chai helado','Bebidas frías','Especias, té negro y leche de avena.',35],['Limonada de lavanda','Bebidas frías','Limón fresco y jarabe de lavanda.',30],['Tostada de aguacate','Desayunos','Masa madre, aguacate, huevo y chile.',56],['Huevos turcos','Desayunos','Yogur, huevos pochados y mantequilla.',62],['Granola de temporada','Desayunos','Yogur, fruta fresca y miel.',48],['Croissant de jamón','Desayunos','Queso gouda, jamón y rúcula.',45],['Bowl mediterráneo','Comidas','Falafel, hummus y vegetales asados.',68],['Sándwich de pollo','Comidas','Pollo especiado, pesto y ensalada.',64],['Pasta de hongos','Comidas','Setas, parmesano y hierbas.',72],['Cheesecake de limón','Postres','Cremoso, ácido y muy fresco.',38],['Roll de canela','Postres','Masa brioche y glaseado de queso.',28],['Brownie de cacao','Postres','Cacao 70%, nueces y sal marina.',32]
];
let products=JSON.parse(localStorage.getItem('huehuecofee-products')||'null')||baseProducts.map((p,i)=>({id:i+1,name:p[0],category:p[1],description:p[2],price:p[3],image:images[p[1]]}));let cart=JSON.parse(localStorage.getItem('huehuecofee-cart')||'[]');let active='Todo',limit=8,english=false;
const $=s=>document.querySelector(s);const grid=$('#productsGrid'); const fmt=n=>'Q'+Number(n).toFixed(2);
const translations={en:{navMenu:'Menu',navStory:'Our story',navVisit:'Visit us',eyebrow:'COFFEE · KITCHEN · COMMUNITY',heroTitle:'Moments that taste like <em>home.</em>',heroText:'Origin coffee, intentionally prepared food and a place to stay a little longer.',viewMenu:'Explore the menu <span>→</span>',findUs:'Find us <span>↗</span>',daily:'Every day',address:'4th Street 6-45',ourSelection:'OUR SELECTION',menuTitle:"Today’s menu",menuSubtitle:'Honest ingredients, nearby producers and recipes that follow the season.',showMore:'See full menu <span>↓</span>',aboutEyebrow:'SINCE 2018',aboutTitle:'Good coffee is an excuse to meet.',aboutText:'Lúmina began around a small bar and a big idea: make daily coffee a more conscious ritual.',aboutLink:'Meet our story <span>→</span>',operations:'CONNECTED OPERATIONS',rolesTitle:'The whole team, in sync.',roleGuest:'Guest',roleGuestTxt:'Browse the menu and build an order before you arrive.',roleWaiter:'Waiter',roleWaiterTxt:'Tables, tickets and tabs at a glance.',roleKitchen:'Kitchen',roleKitchenTxt:'Clear orders, FIFO, in real time.',roleCashier:'Cashier',roleCashierTxt:'Fast payments and each shift under control.',adminAccess:'Admin access',visitEyebrow:'COME VISIT US',visitTitle:'Your table is waiting.',mondayFriday:'Monday — Friday',weekend:'Saturday — Sunday',footer:'Made with care in Guatemala.',yourOrder:'YOUR ORDER',cartTitle:'What you picked',total:'Total',checkout:'Continue order →'}};
function save(){localStorage.setItem('huehuecofee-products',JSON.stringify(products));localStorage.setItem('huehuecofee-cart',JSON.stringify(cart))}function productCard(p){return `<article class="product-card"><div class="product-image"><img loading="lazy" src="${p.image||images[p.category]}" alt="${p.name}"></div><button class="add" data-add="${p.id}" aria-label="Agregar ${p.name}">+</button><div class="product-info"><div><h3>${p.name}</h3><b>${fmt(p.price)}</b></div><p>${p.description}</p></div></article>`}
function render(){let q=$('#searchInput').value.toLowerCase();let list=products.filter(p=>(active==='Todo'||p.category===active)&&(p.name+p.description).toLowerCase().includes(q));grid.innerHTML=list.slice(0,limit).map(productCard).join('')||'<p>No encontramos productos con esa búsqueda.</p>';$('#showMore').style.display=list.length>limit?'block':'none';renderFilters();renderAdmin();}
function renderFilters(){let cats=['Todo',...new Set(products.map(p=>p.category))];$('#filters').innerHTML=cats.map(c=>`<button class="filter ${c===active?'active':''}" data-filter="${c}">${c}</button>`).join('')}
function add(id){let line=cart.find(x=>x.id===id);if(line)line.qty++;else cart.push({id,qty:1});save();renderCart();toast('Agregado a tu orden');}
function renderCart(){let container=$('#cartItems');container.innerHTML=cart.length?cart.map(line=>{let p=products.find(x=>x.id===line.id);if(!p)return '';return `<div class="cart-line"><img src="${p.image||images[p.category]}" alt=""><div><h4>${p.name}</h4><p>${fmt(p.price)}</p></div><div class="quantity"><button data-qty="${p.id}|-1">−</button>${line.qty}<button data-qty="${p.id}|1">+</button></div></div>`}).join(''):'<p style="color:var(--muted)">Aún no has agregado nada.</p>';let total=cart.reduce((sum,l)=>sum+(products.find(p=>p.id===l.id)?.price||0)*l.qty,0);$('#cartTotal').textContent=fmt(total);$('#cartCount').textContent=cart.reduce((n,x)=>n+x.qty,0)}
function renderAdmin(){$('#adminProducts').innerHTML=products.map(p=>`<div class="admin-product"><img src="${p.image||images[p.category]}" alt=""><div><b>${p.name}</b><span>${p.category} · ${fmt(p.price)}</span></div><button class="delete" data-delete="${p.id}" title="Eliminar producto">×</button></div>`).join('')}
function drawer(id){$('#'+id).classList.add('open');$('#overlay').classList.add('show')}function closeAll(){document.querySelectorAll('.drawer').forEach(x=>x.classList.remove('open'));$('#overlay').classList.remove('show');document.querySelectorAll('dialog[open]').forEach(x=>x.close())}function toast(t){let x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
document.addEventListener('click',e=>{let addBtn=e.target.closest('[data-add]');if(addBtn)add(+addBtn.dataset.add);let filter=e.target.closest('[data-filter]');if(filter){active=filter.dataset.filter;limit=8;render()}let qty=e.target.closest('[data-qty]');if(qty){let [id,n]=qty.dataset.qty.split('|').map(Number);let l=cart.find(x=>x.id===id);l.qty+=n;if(l.qty<1)cart=cart.filter(x=>x.id!==id);save();renderCart()}let del=e.target.closest('[data-delete]');if(del){products=products.filter(p=>p.id!==+del.dataset.delete);cart=cart.filter(x=>x.id!==+del.dataset.delete);save();render();renderCart();toast('Producto eliminado')}if(e.target.closest('[data-close]'))closeAll();});
function availableTables(){let active=new Set(JSON.parse(localStorage.getItem('huehuecofee-orders')||'[]').filter(o=>/^Mesa/.test(o.table)&&o.status!=='pagada').map(o=>o.table));let select=$('#tableSelect');select.innerHTML='<option value="">Elige una mesa</option>'+[1,2,3,4,5,6].filter(n=>!active.has(`Mesa 0${n}`)).map(n=>`<option>Mesa 0${n}</option>`).join('')+'<option>Para llevar</option>';}
$('#cartBtn').onclick=()=>drawer('cartDrawer');$('#adminBtn')?.addEventListener('click',()=>drawer('adminDrawer'));$('#overlay').onclick=closeAll;$('#menuBtn').onclick=()=>{document.querySelector('.links').classList.toggle('mobile-links')};$('#showMore').onclick=()=>{limit+=12;render()};$('#searchInput').oninput=()=>{limit=8;render()};$('#addProductBtn').onclick=()=>$('#formDialog').showModal();$('#locationBtn').onclick=()=>$('#visita').scrollIntoView({behavior:'smooth'});$('#checkoutBtn').onclick=()=>{if(!cart.length)return toast('Agrega algo primero.');availableTables();closeAll();$('#tableDialog').showModal()};
$('#productForm').onsubmit=e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));products.unshift({id:Date.now(),...d,price:+d.price,image:d.image||images[d.category]});save();e.target.reset();$('#formDialog').close();render();toast('Producto publicado en el menú')};
$('#tableForm').onsubmit=e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target)),number=String(d.cardNumber||'').replace(/\s/g,'');if(d.payment==='tarjeta'&&(!d.cardName||number.length<16||!/^\d{2}\/\d{2}$/.test(d.cardExpiry||'')||!/^\d{3,4}$/.test(d.cardCvv||'')))return toast('Completa correctamente los datos de la tarjeta.');let orders=JSON.parse(localStorage.getItem('huehuecofee-orders')||'[]');if(/^Mesa/.test(d.table)&&orders.some(o=>o.table===d.table&&o.status!=='pagada'))return toast('Esta mesa acaba de ocuparse. Elige otra.');orders.unshift({id:Date.now().toString().slice(-5),table:d.table,note:d.note,items:cart.map(line=>{let p=products.find(x=>x.id===line.id);return {name:p.name,qty:line.qty,price:p.price}}),status:'pendiente',payment:d.payment,paid:d.payment==='tarjeta',time:new Date().toLocaleTimeString('es-GT',{hour:'2-digit',minute:'2-digit'})});localStorage.setItem('huehuecofee-orders',JSON.stringify(orders));cart=[];save();renderCart();e.target.reset();$('#cardFields').hidden=true;$('#tableDialog').close();toast(d.payment==='tarjeta'?'¡Pago aprobado! Pedido enviado a '+d.table+'!':'¡Pedido enviado a '+d.table+'!')};
$('#paymentMethod').onchange=e=>{$('#cardFields').hidden=e.target.value!=='tarjeta'};
$('#cardNumber').oninput=e=>{let raw=e.target.value.replace(/\D/g,'').slice(0,16);e.target.value=raw.replace(/(.{4})/g,'$1 ').trim();$('#cardPreview').textContent=(raw.slice(-4)||'••••').padStart(4,'•')};$('#cardExpiry').oninput=e=>{let raw=e.target.value.replace(/\D/g,'').slice(0,4);e.target.value=raw.length>2?raw.slice(0,2)+'/'+raw.slice(2):raw};$('#cardName').oninput=e=>$('#cardPreviewName').textContent=e.target.value.toUpperCase()||'NOMBRE EN TARJETA';
$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');$('#themeBtn').textContent=document.body.classList.contains('dark')?'☾':'☼';localStorage.setItem('lumina-theme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('lumina-theme')==='dark')$('#themeBtn').click();
$('#langBtn').onclick=()=>{english=!english;$('#langBtn').textContent=english?'EN':'ES';let d=translations.en;document.querySelectorAll('[data-i18n]').forEach(el=>{let t=d[el.dataset.i18n];if(t)el.innerHTML=english?t:el.dataset.original||(el.dataset.original=el.innerHTML)});$('#searchInput').placeholder=english?'Search your craving':'Busca tu antojo'};render();
render();renderCart();
const workers={mesero:{password:'Mesa2026!',role:'Mesero',name:'Andrea',description:'Gestiona mesas, pedidos y cuentas desde un solo lugar.'},cocina:{password:'Cocina2026!',role:'Cocina',name:'Carlos',description:'Comandas organizadas por hora de llegada (FIFO).'},cajero:{password:'Caja2026!',role:'Caja',name:'Sofía',description:'Controla pagos, órdenes de mostrador y tu turno.'},admin:{password:'Admin2026!',role:'Administrador',name:'María',description:'Supervisa ventas, productos y la operación del día.'}};
function staffView(user){let content=$('#staffContent');$('#staffRole').textContent=user.role.toUpperCase()+' · TURNO ACTIVO';$('#staffGreeting').textContent='Hola, '+user.name+'.';$('#staffDescription').textContent=user.description;let card=(title,text,items)=>`<article class="work-card"><h3>${title}</h3><p>${text}</p>${items?`<ul>${items.map(x=>`<li>${x}</li>`).join('')}</ul>`:''}</article>`;
if(user.role==='Mesero')content.innerHTML=`<div class="table-grid"><div class="table"><b>Mesa 01</b><span>Disponible</span></div><div class="table busy"><b>Mesa 02</b><span>Ocupada · Q186</span></div><div class="table pending"><b>Mesa 03</b><span>Pendiente de pago</span></div><div class="table busy"><b>Mesa 04</b><span>Ocupada · 2 personas</span></div></div><div class="work-grid staff-action">${card('Comanda #108','Mesa 02 · Cliente en mesa',['2 × Cappuccino','1 × Tostada de aguacate','Sin cebolla, por favor'])}${card('Seguimiento','El pedido ya fue enviado a cocina.',['Hora de envío: 10:42','Estado: en preparación','Mesero: Andrea'])}${card('Cuenta de mesa','Total actual Q186.00',['Agregar productos al menú','Registrar observaciones','Cerrar cuenta al cobrar'])}</div>`;
else if(user.role==='Cocina')content.innerHTML=`<div class="order-board"><article class="ticket"><h3>#106 · Mesa 04</h3><p>10:31 · Mesero: Andrea<br><br>2 × Huevos turcos<br>1 × Cold brew cítrico<br><em>Sin picante</em></p><button>Marcar en preparación</button></article><article class="ticket"><h3>#107 · Mostrador</h3><p>10:36 · Caja: Sofía<br><br>1 × Latte de miel<br>1 × Roll de canela</p><button>Marcar en preparación</button></article><article class="ticket ready"><h3>#105 · Mesa 01</h3><p>10:24 · Listo para entregar<br><br>2 × Cappuccino<br>1 × Cheesecake de limón</p><button>Pedido listo ✓</button></article></div>`;
else if(user.role==='Caja')content.innerHTML=`<div class="work-grid">${card('Turno actual','Apertura registrada a las 07:00.',['Fondo inicial: Q500.00','Ventas en efectivo: Q1,840.00','Ventas con tarjeta: Q2,440.00'])}${card('Orden en mostrador','Orden #107 lista para cobro.',['Latte de miel · Q38','Roll de canela · Q28','Total: Q66.00'])}${card('Notificaciones','Barista y cocina actualizan estados.',['#105 listo para entregar','#107 en preparación','Caja conciliada: 98%'])}</div><button class="button primary staff-action" onclick="toast('Pago con tarjeta registrado')">Cobrar con tarjeta →</button>`;
else content.innerHTML=`<div class="work-grid">${card('Ventas del día','Monitorea el desempeño en tiempo real.',['Q4,280.00 vendidos','36 órdenes registradas','Ticket promedio: Q119'])}${card('Más vendidos','Decisiones basadas en el menú real.',['1. Cappuccino · 18 ventas','2. Tostada de aguacate · 14 ventas','3. Latte de miel · 11 ventas'])}${card('Administración','Gestiona el catálogo y los usuarios.',['Crear o editar productos','Activar productos temporalmente','Gestionar perfiles de empleados'])}</div><button class="button primary staff-action" id="adminWorkspaceBtn">Gestionar productos →</button>`;
$('#adminWorkspaceBtn')?.addEventListener('click',()=>drawer('adminDrawer'));
}
if($('#loginBtn')){$('#loginBtn').onclick=()=>$('#loginDialog').showModal();
$('#loginForm').onsubmit=e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));let user=workers[d.username.toLowerCase()];if(!user||user.password!==d.password){$('#loginError').textContent='Usuario o contraseña incorrectos.';return}$('#loginDialog').close();$('#publicSite').hidden=true;$('footer').hidden=true;$('#staffSite').hidden=false;$('#cartBtn').hidden=true;$('#loginBtn').hidden=true;staffView(user);window.scrollTo({top:0,behavior:'smooth'});};
$('#logoutBtn').onclick=()=>{$('#staffSite').hidden=true;$('#publicSite').hidden=false;$('footer').hidden=false;$('#cartBtn').hidden=false;$('#loginBtn').hidden=false;window.scrollTo({top:0,behavior:'smooth'});};}
