const $=s=>document.querySelector(s);
const accounts={mesero:{password:'Mesa2026!',name:'Andrea',role:'Mesero',desc:'Toma órdenes y gestiona las mesas.'},cocina:{password:'Cocina2026!',name:'Carlos',role:'Cocina',desc:'Comandas FIFO e inventario de ingredientes.'},cajero:{password:'Caja2026!',name:'Sofía',role:'Caja',desc:'Pagos de pedidos en mesa o para llevar.'},admin:{password:'Admin2026!',name:'María',role:'Administrador',desc:'Catálogo completo, ventas y productos.'}};
let user=[],waiterCart=[],activeSection='dashboard';
const initialProducts=[['Espresso doble','Café',24],['Cappuccino','Café',32],['Latte de miel','Café',38],['Americano','Café',26],['Flat white','Café',34],['Mocha de la casa','Café',40],['Cold brew cítrico','Bebidas frías',42],['Matcha cloud','Bebidas frías',44],['Té chai helado','Bebidas frías',35],['Limonada de lavanda','Bebidas frías',30],['Tostada de aguacate','Desayunos',56],['Huevos turcos','Desayunos',62],['Granola de temporada','Desayunos',48],['Croissant de jamón','Desayunos',45],['Bowl mediterráneo','Comidas',68],['Sándwich de pollo','Comidas',64],['Pasta de hongos','Comidas',72],['Cheesecake de limón','Postres',38],['Roll de canela','Postres',28],['Brownie de cacao','Postres',32]].map((x,i)=>({id:i+1,name:x[0],category:x[1],price:x[2],description:'Producto HuehueCofee',image:'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80'}));
const getProducts=()=>JSON.parse(localStorage.getItem('huehuecofee-products')||'null')||initialProducts;
const saveProducts=x=>localStorage.setItem('huehuecofee-products',JSON.stringify(x));
const getOrders=()=>JSON.parse(localStorage.getItem('huehuecofee-orders')||'[]');
const saveOrders=x=>localStorage.setItem('huehuecofee-orders',JSON.stringify(x));
const getStock=()=>JSON.parse(localStorage.getItem('huehuecofee-stock')||'null')||[{name:'Granos de café',qty:12,unit:'kg'},{name:'Leche',qty:18,unit:'L'},{name:'Pan artesanal',qty:24,unit:'unidades'},{name:'Huevos',qty:30,unit:'unidades'},{name:'Aguacate',qty:14,unit:'unidades'},{name:'Cacao',qty:4,unit:'kg'}];
const saveStock=x=>localStorage.setItem('huehuecofee-stock',JSON.stringify(x));
const money=n=>'Q'+Number(n).toFixed(2); const total=o=>o.items.reduce((s,x)=>s+x.price*x.qty,0); const items=o=>o.items.map(x=>`${x.qty} × ${x.name}`).join('<br>');
function ticket(o,controls=''){return `<article class="ticket ${o.status==='lista'?'ready':''}"><h3>#${o.id} · ${o.table}</h3><p>${o.time} · <b>${o.status}</b>${o.paid?'<br>✓ Pagado con tarjeta':''}<br><br>${items(o)}${o.note?`<br><br><em>Nota: ${o.note}</em>`:''}</p>${controls}</article>`}
function renderSection(section,orders,products,out){let stock=getStock(),sales=orders.filter(o=>o.paid).reduce((s,o)=>s+total(o),0),catalog=products.map(p=>`<article class="catalog-row"><img src="${p.image}" alt=""><div><b>${p.name}</b><span>${p.category} · ${money(p.price)}</span></div>${user.role==='Administrador'?`<button data-edit="${p.id}">Editar</button><button class="delete" data-delete="${p.id}">×</button>`:''}</article>`).join('');
if(section==='menu'){out.innerHTML=`<p class="eyebrow">CATÁLOGO</p><h2 class="board-title">Gestión del menú</h2>${user.role==='Administrador'?'<button class="button primary" id="newProduct">+ Agregar producto</button>':''}<div class="admin-catalog staff-action">${catalog}</div>`;return}
if(section==='mesas'){let tables=[1,2,3,4,5,6].map(n=>{let name=`Mesa 0${n}`,o=orders.find(x=>x.table===name&&x.status!=='pagada');return `<article class="table ${o?'busy':''}"><b>${name}</b><span>${o?'Ocupada · #'+o.id:'Disponible'}</span></article>`}).join('');out.innerHTML=`<p class="eyebrow">SALÓN</p><h2 class="board-title">Mesas y órdenes</h2><div class="table-grid">${tables}</div><div class="order-board staff-action">${orders.filter(o=>o.status!=='pagada').map(o=>ticket(o)).join('')||'<p>No hay órdenes activas.</p>'}</div>`;return}
if(section==='cocina'){out.innerHTML=`<p class="eyebrow">COMANDAS · FIFO</p><h2 class="board-title">Preparación en cocina</h2><div class="order-board">${orders.filter(o=>o.status!=='pagada').map(o=>ticket(o,user.role==='Cocina'&&o.status!=='lista'?`<button data-kitchen="${o.id}">${o.status==='pendiente'?'Preparar pedido':'Marcar como listo ✓'}</button>`:'')).join('')||'<p>Sin comandas pendientes.</p>'}</div>`;return}
if(section==='inventario'){out.innerHTML=`<p class="eyebrow">EXISTENCIAS</p><h2 class="board-title">Inventario de ingredientes</h2><div class="stock-grid">${stock.map((x,i)=>`<article class="stock-item ${x.qty<6?'low':''}"><b>${x.name}</b><span>${x.qty} ${x.unit}</span>${['Cocina','Administrador'].includes(user.role)?`<div><button data-stock="${i}|-1">−</button><button data-stock="${i}|1">+</button></div>`:''}</article>`).join('')}</div>`;return}
out.innerHTML=`<p class="eyebrow">RESUMEN DEL NEGOCIO</p><h2 class="board-title">Reportes y ventas</h2><div class="work-grid"><article class="work-card"><h3>Ventas cobradas</h3><p class="cash-total">${money(sales)}</p><p>${orders.filter(o=>o.paid).length} órdenes pagadas.</p></article><article class="work-card"><h3>Órdenes activas</h3><p class="cash-total">${orders.filter(o=>o.status!=='pagada').length}</p><p>Pedidos en operación.</p></article><article class="work-card"><h3>Productos activos</h3><p class="cash-total">${products.length}</p><p>Disponibles en el menú.</p></article></div>`}
function render(){let orders=getOrders(),out=$('#dashboardContent'),products=getProducts();$('#roleLabel').textContent=user.role.toUpperCase()+' · TURNO ACTIVO';$('#greeting').textContent=activeSection==='dashboard'?'Hola, '+user.name+'.':activeSection[0].toUpperCase()+activeSection.slice(1);$('#roleDescription').textContent=activeSection==='dashboard'?user.desc:'Consulta y administra la información de HuehueCofee.';if(activeSection!=='dashboard'){renderSection(activeSection,orders,products,out);return}
if(user.role==='Mesero'){let tables=[1,2,3,4,5,6].map(n=>`Mesa 0${n}`).filter(name=>!orders.some(o=>o.table===name&&o.status!=='pagada')).map(name=>`<button class="table" data-table="${name}"><b>${name}</b><span>Disponible</span></button>`).join('');let first=orders.some(o=>o.table==='Mesa 01'&&o.status!=='pagada')?(tables.match(/data-table="(Mesa \d+)"/)||[, 'Sin mesas libres'])[1]:'Mesa 01';let menu=products.map(p=>`<button class="menu-pick" data-add-product="${p.id}"><b>${p.name}</b><span>${money(p.price)}</span></button>`).join('');let cart=waiterCart.map(x=>`<li>${x.qty} × ${x.name} <button data-waiter-remove="${x.id}">×</button></li>`).join('')||'<li>Selecciona productos del menú.</li>';out.innerHTML=`<p class="eyebrow">MESAS DISPONIBLES</p><div class="table-grid">${tables||'<p>No hay mesas disponibles.</p>'}</div><div class="waiter-layout staff-action"><section class="work-card"><h3>Tomar orden <small id="selectedTable">${first}</small></h3><div class="waiter-menu">${menu}</div></section><section class="work-card"><h3>Orden actual</h3><ul>${cart}</ul><label>Observaciones<input id="waiterNote" placeholder="Ej. sin azúcar" /></label><button class="button primary full" id="sendWaiterOrder">Enviar a cocina →</button></section></div><h2 class="board-title">Órdenes activas</h2><div class="order-board">${orders.filter(o=>o.status!=='pagada').map(o=>ticket(o)).join('')||'<p>No hay órdenes activas.</p>'}</div>`}
else if(user.role==='Cocina'){let stock=getStock();out.innerHTML=`<p class="eyebrow">COMANDAS · ORDEN DE LLEGADA</p><h2 class="board-title">Preparación en cocina</h2><div class="order-board">${orders.filter(o=>o.status!=='pagada').map(o=>ticket(o,o.status!=='lista'?`<button data-kitchen="${o.id}">${o.status==='pendiente'?'Preparar pedido':'Marcar como listo ✓'}</button>`:'')).join('')||'<p>Sin comandas pendientes.</p>'}</div><h2 class="board-title">Inventario de ingredientes</h2><div class="stock-grid">${stock.map((x,i)=>`<article class="stock-item ${x.qty<6?'low':''}"><b>${x.name}</b><span>${x.qty} ${x.unit}</span><div><button data-stock="${i}|-1">−</button><button data-stock="${i}|1">+</button></div></article>`).join('')}</div>`}
else if(user.role==='Caja'){let open=orders.filter(o=>!o.paid&&o.status!=='pagada');let sales=orders.filter(o=>o.paid).reduce((s,o)=>s+total(o),0);out.innerHTML=`<div class="work-grid"><article class="work-card"><h3>Ventas cobradas</h3><p class="cash-total">${money(sales)}</p><p>${orders.filter(o=>o.paid).length} órdenes pagadas.</p></article><article class="work-card"><h3>Por cobrar</h3><p class="cash-total">${open.length}</p><p>Órdenes pendientes de pago.</p></article><article class="work-card"><h3>Turno</h3><p>Fondo de apertura: Q500.00</p><p>Disponible para efectivo o tarjeta.</p></article></div><h2 class="board-title">Cobrar órdenes</h2><div class="order-board">${open.map(o=>ticket(o,`<p><b>Total: ${money(total(o))}</b></p><button data-pay="${o.id}|efectivo">Efectivo</button> <button data-pay="${o.id}|tarjeta">Tarjeta</button>`)).join('')||'<p>No hay pagos pendientes.</p>'}</div>`}
else {let sales=orders.filter(o=>o.paid).reduce((s,o)=>s+total(o),0);out.innerHTML=`<div class="work-grid"><article class="work-card"><h3>Ventas cobradas</h3><p class="cash-total">${money(sales)}</p><p>${orders.length} órdenes registradas.</p></article><article class="work-card"><h3>Operación</h3><p>${orders.filter(o=>o.status==='pendiente').length} pedidos pendientes</p><p>${orders.filter(o=>o.status==='lista').length} pedidos listos</p></article><article class="work-card"><h3>Catálogo</h3><p>${products.length} productos publicados.</p><button class="button primary" id="newProduct">+ Agregar producto</button></article></div><h2 class="board-title">Administrar menú</h2><div class="admin-catalog">${products.map(p=>`<article class="catalog-row"><img src="${p.image}" alt=""><div><b>${p.name}</b><span>${p.category} · ${money(p.price)}</span></div><button data-edit="${p.id}">Editar</button><button class="delete" data-delete="${p.id}">×</button></article>`).join('')}</div>`}}
function formProduct(p={}){return `<form id="catalogForm" class="work-card"><h3>${p.id?'Editar producto':'Nuevo producto'}</h3><input type="hidden" name="id" value="${p.id||''}"><label>Nombre<input required name="name" value="${p.name||''}"></label><label>Descripción<input required name="description" value="${p.description||''}"></label><label>Precio<input required name="price" type="number" min="1" step=".5" value="${p.price||''}"></label><label>Categoría<input required name="category" value="${p.category||'Café'}"></label><label>Imagen URL<input name="image" value="${p.image||''}"></label><button class="button primary full">Guardar producto</button></form>`}
function applyRoleNavigation(){document.querySelectorAll('#panelNav [data-roles]').forEach(link=>{link.hidden=!link.dataset.roles.split(',').includes(user.role)});}
$('#loginForm').onsubmit=e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target)),candidate=accounts[d.username.toLowerCase()];if(!candidate||candidate.password!==d.password){$('#loginError').textContent='Usuario o contraseña incorrectos.';return}user=candidate;waiterCart=[];activeSection='dashboard';applyRoleNavigation();$('#loginPage').hidden=true;$('#dashboard').hidden=false;render()};
$('#logout').onclick=()=>{user=null;$('#dashboard').hidden=true;$('#loginPage').hidden=false;$('#loginForm').reset()};
$('#panelNav').addEventListener('click',e=>{let link=e.target.closest('[data-section]');if(!link||!user||link.hidden)return;e.preventDefault();activeSection=link.dataset.section;document.querySelectorAll('#panelNav a').forEach(a=>a.classList.toggle('active',a===link));render();$('#dashboardContent').scrollIntoView({behavior:'smooth',block:'start'})});
document.addEventListener('click',e=>{let b=e.target.closest('[data-kitchen],[data-pay],[data-stock],[data-add-product],[data-waiter-remove],[data-table],[data-delete],[data-edit],#newProduct,#sendWaiterOrder');if(!b||!user)return;
if(b.dataset.kitchen){let os=getOrders(),o=os.find(x=>x.id===b.dataset.kitchen);o.status=o.status==='pendiente'?'en preparación':'lista';saveOrders(os);render()}
if(b.dataset.pay){let [id,method]=b.dataset.pay.split('|'),os=getOrders(),o=os.find(x=>x.id===id);o.paid=true;o.payment=method;o.status='pagada';saveOrders(os);render()}
if(b.dataset.stock){let [i,d]=b.dataset.stock.split('|').map(Number),s=getStock();s[i].qty=Math.max(0,s[i].qty+d);saveStock(s);render()}
if(b.dataset.table){document.querySelectorAll('[data-table]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('#selectedTable').textContent=b.dataset.table}
if(b.dataset.addProduct){let p=getProducts().find(x=>x.id===+b.dataset.addProduct),x=waiterCart.find(x=>x.id===p.id);x?x.qty++:waiterCart.push({...p,qty:1});render()}
if(b.dataset.waiterRemove){let x=waiterCart.find(x=>x.id===+b.dataset.waiterRemove);x.qty--;if(x.qty<1)waiterCart=waiterCart.filter(x=>x.id!==+b.dataset.waiterRemove);render()}
if(b.id==='sendWaiterOrder'){if(!waiterCart.length)return;let os=getOrders(),table=$('#selectedTable').textContent;if(!/^Mesa/.test(table))return;os.unshift({id:Date.now().toString().slice(-5),table,note:$('#waiterNote').value,items:waiterCart.map(x=>({name:x.name,qty:x.qty,price:x.price})),status:'pendiente',payment:'pendiente',paid:false,time:new Date().toLocaleTimeString('es-GT',{hour:'2-digit',minute:'2-digit'})});saveOrders(os);waiterCart=[];render()}
if(b.id==='newProduct')$('#dashboardContent').insertAdjacentHTML('afterbegin',formProduct());
if(b.dataset.edit){let p=getProducts().find(x=>x.id===+b.dataset.edit);$('#dashboardContent').insertAdjacentHTML('afterbegin',formProduct(p));window.scrollTo({top:0,behavior:'smooth'})}
if(b.dataset.delete){saveProducts(getProducts().filter(x=>x.id!==+b.dataset.delete));render()}});
document.addEventListener('submit',e=>{if(e.target.id!=='catalogForm')return;e.preventDefault();let d=Object.fromEntries(new FormData(e.target)),ps=getProducts(),i=ps.findIndex(x=>x.id===+d.id),p={...d,id:d.id?+d.id:Date.now(),price:+d.price,image:d.image||'https://images.unsplash.com/photo-1514432324607-4d71bcdd2085?auto=format&fit=crop&w=600&q=80'};if(i<0)ps.unshift(p);else ps[i]=p;saveProducts(ps);render()});
window.addEventListener('storage',e=>{if(['huehuecofee-orders','huehuecofee-products','huehuecofee-stock'].includes(e.key)&&user)render()});
